name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .
    - name: where is my exe
      run: |
        cd dist && ls -R
    - uses: actions/upload-artifact@v2
      with:
        name: mediaPipeFaceTracking
        path: dist/mediaPipeFaceTracking.exe
